### PR TITLE
Add a Motorcycle.js solution

### PR DESCRIPTION
**Pull request by TylorS**
This simply adds a [Motorcycle.js](http://github.com/motorcyclejs) solution.
Under the hood this application uses [most.js](https://github.com/cujojs/most) for it's stream/observable implementation, [snabbdom](https://github.com/paldepind/snabbdom) for it's virtual-dom implementation, and [rackt/history](https://github.com/rackt/history) to keep the addressbar/history up-to-date.

### CODE REVIEW

**Comment by DerekCuevas** [comment]
Awesome, thanks!

One problem: 
It looks like you accidentally checked your dist/ folder into your solution and have added a giant 10,181 line addition here [motorcyclejs-solution/dist/app.js](https://github.com/TylorS/friend-list/blob/master/motorcyclejs-solution/dist/app.js). Will you please revert and squash this out of the commit?

**Comment by TylorS** [comment]
Yes! Sorry about that.

**Comment by TylorS** [comment]
Done!

**Comment by DerekCuevas** [comment]
No problem! 

Two more very minor issues:
- Can you please remove 'npm install' from your npm start script? Just add 'npm install' to your README under 'To run'. This would make it more consistent with the other examples, also a little easier to test in my opinion. So change the start script to this:

``` sh
"start": "npm run build && npm run server",
```
- When the query is empty the URL should be changed back to 'http://localhost:3474/'. Your solution leaves the query param 'q' on the URL with no value - (like so 'http://localhost:3474/?q='). See the other solutions for expected behavior. Do you thing you could correct this as well?

**Comment by TylorS** [comment]
Yes, both of those are very easy fixes.

**Comment by DerekCuevas** [comment]
Sweet, other than that everything looks great. Thanks!

**Comment by TylorS** [comment]
Should be good now

**Comment by TylorS** [comment]
Thank you! And thank you for doing this challenge :+1:

**Pull request merged**
