### PR TITLE
Cycle.js solution (reusing React views)

### PR DESCRIPTION
**Pull request by justinwoo**
I made a Cycle.js solution reusing most of your React views, with some tweaks to eliminate some component state level things that I found didn't make much sense.

Some things I ran into that I was a little confused about:
- You have multiple actions firing off when this first loads (partially due to react-router/history). Didn't expect this and it makes for a kind of rough looking load, but I guess this is expected.
- You have `debounce` settings around that aren't being set or just use the default prop value of 0? I didn't really bother to implement this, though it would be easy to do with some debouncing and flatmapping with takeUntil/amb.

I mostly tried to understand what your intent was based on the GIF, the specs, and some of your previous code, but I might have missed something you wanted.

### CODE REVIEW

**Comment by DerekCuevas** [comment]
Thanks!

Give me some time to review this, I'm not very familiar with Cycle.js, so it would be nice if someone with more expertise could look over this. However, this solution looks very clean, so thank you very much.

To address your two points:
- Multiple actions on load seed the store. If you find (or have found) a better way to do this, go for it. Just remember to seed from the current URL state. For example, if the user navigates to '/?q=superman' only one API search should be made with the query = 'superman' on page load.
- Yes I'm aware of the unused debounce code in the SearchInput component, that's old and should probably be removed. It should be turned into a stateless, functional component to be consistent with the others.

**Comment by DerekCuevas** [comment]
@justinwoo I updated the SearchInput component and removed the unneeded debounce. You can use the updated component in your solution if you wish.

**Comment by justinwoo** [comment]
Cool. I didn't really need a lot of the code in SearchInput though, so I took it out.

**Comment by DerekCuevas** [comment]
Ok awesome, this looks like a great solution, it doesn't use redux, but that's ok i'll merge it in. Will you please add one or two sentences to your README documenting the choice to use Cycle and why it fits the problem?

**Comment by justinwoo** [comment]
All right, I updated the README. Let me know if you think there's anything missing.

**Comment by DerekCuevas** [comment]
Looks great. Thanks!

**Pull request merged**
