### PR TITLE
add redux-loop solution

### PR DESCRIPTION
**Pull request by lukewestby**
Had some time tonight to do this after all. Let me know what you think!

### CODE REVIEW

**Comment by DerekCuevas** [comment]
This looks great at first glance, however you may be pushing to history more than is needed. Check the store.subscribe call [here](https://github.com/DerekCuevas/friend-list/pull/4/files#diff-1c0671d6ad1ecc3851cdfaaf62d6844bR14). The listener you have attached to the store will be called both when setting the query, and when setting the results. I think it's best to only push to history when you set the query.

I could be wrong I haven't had time to fully look over the example yet, I will do that soon. Thanks for contributing!

**Comment by lukewestby** [comment]
Thanks for catching that! It was pushing to history way more than needed. Updated!

I think I'll bring in some of the other implementation details from the observable examples to improve on the things I brought over from the imperative example. In the mean time let me know if you have any more concerns or suggestions.

**Comment by DerekCuevas** [comment]
Yeah I think bringing in more code from the observable examples would work well. I would like to see more examples that don't rely on react lifecycle methods like 'componentDidMount' and 'componentWillReceiveProps' to orchestrate actions. What do you think about this?

Also, I have cleaned up some unneeded, old code in the current examples (mostly in react components), you should update your branch to be more consistent with this if needed.

**Comment by lukewestby** [comment]
That all sounds good to me. Question for you: would you prefer examples adhere to the existing directory structure or would it be okay if I laid this example out more like I would structure an Elm app?

**Comment by DerekCuevas** [comment]
I think it would benefit everybody if the solutions were as diverse as possible, so yes structuring your solution more like an Elm app could work well. Go for it if you see fit!

**Comment by lukewestby** [comment]
Awesome, I'll keep working on this over the next few days and ping you when I feel like it's finished. Thanks for your help!

**Comment by DerekCuevas** [comment]
Ping @lukewestby, are you still working on this? Would you like me to merge this version of the redux-loop solution for now?

**Comment by lukewestby** [comment]
Hey! Sorry, I'm going to get to it at some point but we're gonna be pretty busy at Raise for at least another couple of weeks so I can't say for sure when it'll be finished. If you'd like to close this to keep things clean on your repo that'd be cool with me, I've got this written down in our OSS backlog.

**Comment by DerekCuevas** [comment]
No problem!
I don't mind leaving this open, looking forward to your solution.

**Pull request closed without merging**
